"""Unit tests for POST/GET /api/documents with Storage and DB mocked.

Covers rejection (oversize, wrong type incl. renamed .exe->.pdf, >10 files) and
the happy path (row created, file stored, status reaches review via the stub).
Storage/DB are MagicMocks injected through FastAPI dependency overrides so no
network or real Supabase is touched.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any
from unittest.mock import MagicMock

import pytest
from fastapi.testclient import TestClient

import app.services.ingestion as ingestion
from app.main import app
from app.routes.documents import get_documents_repo, get_storage_repo

PNG = b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR" + b"\x00" * 32
PDF = b"%PDF-1.7\n%%EOF"
JPEG = b"\xff\xd8\xff\xe0\x00\x10JFIF" + b"\x00" * 16


@pytest.fixture(autouse=True)
def _no_stub_delay(monkeypatch: pytest.MonkeyPatch) -> None:
    # Keep the queued->processing->review stub instant so TestClient's
    # synchronous background-task execution does not sleep.
    monkeypatch.setattr(ingestion, "STATUS_STUB_DELAY_SECONDS", 0.0)


@pytest.fixture
def storage() -> MagicMock:
    return MagicMock(name="StorageRepo")


@pytest.fixture
def documents() -> MagicMock:
    repo = MagicMock(name="DocumentsRepo")
    # create() echoes back a queued row; id is generated by the service.
    repo.create.side_effect = lambda **kw: {**kw, "status": "queued"}
    return repo


@pytest.fixture
def client(storage: MagicMock, documents: MagicMock) -> Iterator[TestClient]:
    app.dependency_overrides[get_storage_repo] = lambda: storage
    app.dependency_overrides[get_documents_repo] = lambda: documents
    with TestClient(app) as test_client:
        yield test_client
    app.dependency_overrides.clear()


def _files(*items: tuple[str, bytes]) -> list[tuple[str, tuple[str, bytes, str]]]:
    return [("files", (name, data, "application/octet-stream")) for name, data in items]


def test_happy_path_creates_row_stores_file_and_reaches_review(
    client: TestClient, storage: MagicMock, documents: MagicMock
) -> None:
    response = client.post("/api/documents", files=_files(("invoice.png", PNG)))

    assert response.status_code == 201
    body = response.json()
    assert len(body) == 1
    assert body[0]["status"] == "queued"
    document_id = body[0]["document_id"]

    # Bucket ensured + file uploaded to {user_id}/{document_id}/{filename}.
    storage.ensure_bucket.assert_called_once()
    storage.upload.assert_called_once()
    upload_kwargs = storage.upload.call_args.kwargs
    assert upload_kwargs["path"].endswith(f"/{document_id}/invoice.png")
    assert upload_kwargs["content_type"] == "image/png"
    assert upload_kwargs["data"] == PNG

    # documents row created queued.
    documents.create.assert_called_once()
    assert documents.create.call_args.kwargs["filename"] == "invoice.png"

    # Background stub walked the status: processing then review.
    statuses = [c.kwargs["status"] for c in documents.set_status.call_args_list]
    assert statuses == ["processing", "review"]


def test_multiple_files_accepted(
    client: TestClient, storage: MagicMock, documents: MagicMock
) -> None:
    response = client.post(
        "/api/documents",
        files=_files(("a.pdf", PDF), ("b.jpg", JPEG), ("c.png", PNG)),
    )
    assert response.status_code == 201
    assert len(response.json()) == 3
    assert storage.upload.call_count == 3
    assert documents.create.call_count == 3


def test_rejects_oversized_file(
    client: TestClient, storage: MagicMock, documents: MagicMock
) -> None:
    big = PNG + b"\x00" * (10 * 1024 * 1024 + 1)
    response = client.post("/api/documents", files=_files(("big.png", big)))

    assert response.status_code == 422
    detail = response.json()["detail"]
    assert detail["results"][0]["accepted"] is False
    assert "limit" in detail["results"][0]["error"]
    # All-or-nothing: nothing stored or created.
    storage.upload.assert_not_called()
    documents.create.assert_not_called()


def test_rejects_wrong_type_renamed_exe_as_pdf(
    client: TestClient, storage: MagicMock, documents: MagicMock
) -> None:
    exe = b"MZ\x90\x00" + b"\x00" * 64
    response = client.post("/api/documents", files=_files(("malware.pdf", exe)))

    assert response.status_code == 422
    detail = response.json()["detail"]
    assert detail["results"][0]["accepted"] is False
    assert "unsupported file type" in detail["results"][0]["error"]
    storage.upload.assert_not_called()
    documents.create.assert_not_called()


def test_mixed_batch_is_all_or_nothing(
    client: TestClient, storage: MagicMock, documents: MagicMock
) -> None:
    # One good file, one bad: the whole batch is rejected, nothing stored.
    response = client.post(
        "/api/documents",
        files=_files(("good.pdf", PDF), ("bad.pdf", b"MZ" + b"\x00" * 20)),
    )
    assert response.status_code == 422
    results = response.json()["detail"]["results"]
    assert [r["accepted"] for r in results] == [True, False]
    storage.upload.assert_not_called()
    documents.create.assert_not_called()


def test_rejects_more_than_ten_files(
    client: TestClient, storage: MagicMock, documents: MagicMock
) -> None:
    response = client.post(
        "/api/documents",
        files=_files(*[(f"f{i}.png", PNG) for i in range(11)]),
    )
    assert response.status_code == 400
    assert "1..10" in response.json()["detail"]
    storage.upload.assert_not_called()
    documents.create.assert_not_called()


def test_list_documents_returns_paged_items(client: TestClient, documents: MagicMock) -> None:
    rows: list[dict[str, Any]] = [
        {
            "id": "11111111-1111-1111-1111-111111111111",
            "filename": "a.pdf",
            "status": "review",
            "doc_type": None,
            "created_at": "2026-07-07T10:00:00+00:00",
        }
    ]
    documents.list_for_user.return_value = (rows, 5)

    response = client.get("/api/documents", params={"status": "review", "limit": 1, "offset": 2})

    assert response.status_code == 200
    body = response.json()
    assert body["total"] == 5
    assert body["limit"] == 1
    assert body["offset"] == 2
    assert body["items"][0]["filename"] == "a.pdf"
    assert body["items"][0]["status"] == "review"
    call = documents.list_for_user.call_args.kwargs
    assert call["status"] == "review"
    assert call["limit"] == 1
    assert call["offset"] == 2


def test_list_documents_rejects_bad_status(client: TestClient) -> None:
    response = client.get("/api/documents", params={"status": "nonsense"})
    assert response.status_code == 422
