"""Static metadata for the 5 curated demo documents (T9).

Fixed `document_id`s so seeding is idempotent (re-running the seed script
recognizes existing rows by id instead of creating duplicates) and so both
`scripts/seed_demo.py` and `GET /api/demo/samples` (`app/routes/demo.py`) share
one source of truth for filenames/difficulty/description. Fixture *bytes* are
generated by the seed script itself (see docs/decisions.md); this module only
carries the metadata needed to seed and to render the /demo entry page cards.
"""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from app.config import DEMO_USER_ID

__all__ = ["DEMO_DOCUMENTS", "DEMO_DOCUMENT_IDS", "DemoDocSpec"]


@dataclass(frozen=True)
class DemoDocSpec:
    """One curated demo document: fixed id + display metadata for the card."""

    key: str
    document_id: UUID
    filename: str
    difficulty: str
    title: str
    description: str


DEMO_DOCUMENTS: tuple[DemoDocSpec, ...] = (
    DemoDocSpec(
        key="clean_text",
        document_id=UUID("00000000-0000-0000-0000-0000000000d1"),
        filename="rahunok_chystyi.pdf",
        difficulty="легкий",
        title="Чистий текстовий PDF",
        description="Born-digital рахунок з реальним текстовим шаром — найпростіший кейс.",
    ),
    DemoDocSpec(
        key="good_scan",
        document_id=UUID("00000000-0000-0000-0000-0000000000d2"),
        filename="rahunok_skan.pdf",
        difficulty="середній",
        title="Скан хорошої якості",
        description="PDF без текстового шару (лише зображення сторінки) — маршрут vision.",
    ),
    DemoDocSpec(
        key="low_quality_photo",
        document_id=UUID("00000000-0000-0000-0000-0000000000d3"),
        filename="rahunok_foto.jpg",
        difficulty="складний",
        title="Фото низької якості",
        description="Фото телефоном: невеликий поворот, шум і сильне стиснення JPEG.",
    ),
    DemoDocSpec(
        key="multi_page",
        document_id=UUID("00000000-0000-0000-0000-0000000000d4"),
        filename="rahunok_bagatostorinkovyi.pdf",
        difficulty="середній",
        title="Багатосторінковий рахунок",
        description="Рахунок із великою кількістю позицій, що займає кілька сторінок.",
    ),
    DemoDocSpec(
        key="arithmetic_error",
        document_id=UUID("00000000-0000-0000-0000-0000000000d5"),
        filename="rahunok_pomylka.pdf",
        difficulty="складний",
        title="Рахунок з помилкою в сумі",
        description="Навмисна арифметична помилка — демонструє потік перевірки червоних полів.",
    ),
)

DEMO_DOCUMENT_IDS: frozenset[UUID] = frozenset(spec.document_id for spec in DEMO_DOCUMENTS)


def is_demo_document_id(document_id: UUID) -> bool:
    """True if `document_id` is one of the 5 fixed demo documents."""
    return document_id in DEMO_DOCUMENT_IDS


def is_demo_user(user_id: UUID) -> bool:
    """True if `user_id` is the fixed demo user (see `app.config.DEMO_USER_ID`)."""
    return user_id == DEMO_USER_ID
